[package]
name = "Pictura"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.21", features = ["derive"]}
iced = "0.10.0"
iced_futures = "0.7.0"
iced_graphics = "0.9.0"
iced_native = "0.10.3"
screenshots = "0.7.3"
